### ISSUE TITLE
Setup database for oTree application and create `users` table

### ISSUE THREAD

**Issue by michplunkett** [prijatelilab/PrijateliTree#4]
## What Issue Are You Seeing or What Feature Needs To Be Added?
Setup database connection and allow for the creation of unique users within the application. For this to be complete, we'll require tests showing that the routes, etc. work.

## General Questions
- [ ] Are we going to require authentication with third-party servers (Google, etc.)?
- [ ] What should we require in terms of passwords (strength, length, etc.)?

**Comment by anisfeld** [comment]
We don't think we can do logins with passwords for the users of the game, because they don't have the technology to support it. E.g. many students don't have email addresses. and kids will definitely forget their passwords.

- We're going to talk to our partners on Wendesday about what they think is a reasonable way to proceed.
- E.g. could we use  first name + last name by date of birth authentication?

**Comment by michplunkett** [comment]
It's not really secure, but provided you're fine with that, we could make that work.
